---

title: 'StevenCombs.com'
logo: '/images/design/steven-square.svg'
description: 'Thoughts from Steven as he goes "combsing through the minutia" to discover tech, retro-computing, gadgets, Google, higher education, physical computing, and sci-fi.'
google_analytics: UA-1632774-9
name: 'Steven B. Combs'
email: 'steven.combs@gmail.com'
tagline: 'Combsing through the minutia…'
url: 'https://www.stevencombs.com'

lsi: false
comments: true
highlighter: rouge

themed:
 highlight_color: '#3498db'
 show_disclaimer: true

tipue_search:
  include:
    pages: true

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - .DS*
