--- 
exclude: 
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
lsi: false
markdown: kramdown
pygments: true
theme: 
  email: steven.combs@gmail.com
  google_analytics_key: UA-xxxx-x
  highlight_color: "#3498db"
  name: "Steven B. Combs, Ph.D."
  show_disclaimer: true
  social:
  	gplus: +StevenCombsPhD
  	linkedin: stevencombs
    twitter: StevenCombs
    github: stevencombs
    # facebook: steven.b.combs
    tumblr: stevencombs
# tagline: "Combsing through the minutia"
url: "http://www.stevencombs.com"