---
exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
lsi: false
comments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "superscript", "strikethrough"]
pygments: true
theme:
  email: steven.combs@gmail.com
  google_analytics_key: UA-1632774-9
  highlight_color: "#3498db"
  name: "Steven B. Combs, Ph.D."
  show_disclaimer: true
  social:
    gplus: +StevenCombsPhD
    linkedin: stevencombs
    twitter: StevenCombs
    github: stevencombs
    tumblr: stevencombs
    facebook: steven.b.combs
tagline: "Combsing through the minutia"
url: "http://www.stevencombs.com"
