---

title: "Steven Combs' Blog"
logo: /images/design/steven-square.svg
description: "Combsing through the minutia"
show_downloads: true
google_analytics: UA-1632774-9
name: "Steven Combs"
tagline: "Combsing through the minutia"
url: "https://www.stevencombs.com"

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - .DS*

lsi: false
comments: true
highlighter: rouge

themed:
 email: steven.combs@gmail.com
 highlight_color: "#3498db"
 show_disclaimer: true

tipue_search:
  include:
    pages: true
