---

name: "Steven Combs"
description: "Steven Combs’ Blog"
tagline: "Combsing through the minutia"
url: "http://www.stevencombs.com"

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
lsi: false
comments: true
# markdown: redcarpet
# redcarpet:
#  extensions: ["smart", "strikethrough", "superscript", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

theme_settings:
  email: steven.combs@gmail.com
  google_analytics_key: UA-1632774-9
  highlight_color: "#3498db"
  name: "Steven Combs"
  show_disclaimer: true
  social:
    gplus: +StevenCombsPhD
    linkedin: stevencombs
    twitter: StevenCombs
    github: stevencombs
    tumblr: stevencombs
    facebook: steven.b.combs
